### ISSUE TITLE
Backend-frontend connection

### ISSUE THREAD

**Issue by atyranski** [miniprojectPythonGame/Merged#1]
1) będę potrzebował jeszcze w heroes poza hero_class to jeszcze jakiś numerek z jakiego avatara gość korzysta (generalnie nie mamy ich więcej niż 3), bo w rejestracji jest też opcja wybrania avatara no i avatar jest zależny od klasy (a same obrazki będą już w plikach klienta, więc nie trza ich pobierać czy coś, tylko potrzebuję jeszcze jakiś numerek jakiego avatara do kogo wyświetlać)

**Comment by Viciooo** [comment]
btw ten error przy dodawaniu to wina tego, że dodałem postać lokalnie przed dodanie do bazy - postać w konstruktorze wywoływała query do bazy o generowanie sklepiku, ale jej heroID tam nie było.

**Comment by Viciooo** [comment]
```
    def createHero(self, avatar_id, name, className, strength, intelligence, dexterity, constitution,
                   luck, persuasion, trade, leadership, protection, initiative):
        # className in ('a','w','m')
        try:
            conn, cursor = connect_to_db()
            cursor.execute("SELECT add_hero(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                           (avatar_id, name, self.UID, className, strength, intelligence, dexterity, constitution,
                            luck, persuasion, trade, leadership, protection, initiative))
            conn.commit()
            disconnect_from_db(conn, cursor)
            newHero = Hero(avatar_id, name, className, 0, strength, intelligence, dexterity, constitution,
                           luck, persuasion, trade, leadership, protection, initiative)
            self.Heroes[int(cursor.fetchall()[0])] = newHero

        except Exception as error:
            print(error)

```

Solved - podaj mi jeszcze tylko dokładny przedział avatar_id. 0 - 2 czy 1 - 3 albo inaczej. Dodam w bazie i backendzie walidację

**Comment by atyranski** [comment]
oks doks, czyli jak sobie pullnę to już tego errora nie będzie + dzięki za ten avatar_id
