### ISSUE TITLE
Kupowanie w armor shopie

### ISSUE THREAD

**Issue by atyranski** [miniprojectPythonGame/Merged#10]
![image](https://user-images.githubusercontent.com/72259657/167274191-9fb7dd7e-550f-493f-8d5d-148f6776f327.png)
wywołuję tą funkcję do kupowania i podaję id z listy tych itemów z armorshop'a dla danego hero i podaję typ shopa z enuma i wywala taki błąd - ale jak to się naprawi to kupowanie w sklepach będzie w zasadzie zrobione, bo potem magic i weapon to będzie już copy-paste

**Comment by Viciooo** [comment]
wydaje mi się, że musisz dać 
`hero.buy_from_shop(item.id,ShopType.ArmourShop.value) `
zamiast
![image](https://user-images.githubusercontent.com/72527323/167289578-886e8a1f-f2a2-4676-ae1d-9d911ced9161.png)
Oprócz tego id itemu to item_id, a nie id - chyba, że robiłeś jakieś mapowanie 
![image](https://user-images.githubusercontent.com/72527323/167289619-a8964780-4842-445b-9f84-4c7f25eaa2a5.png)
