### ISSUE TITLE
Quest Bot potrzebuje get_statistics()

### ISSUE THREAD

**Issue by atyranski** [miniprojectPythonGame/Merged#11]
Robię walkę w questach z botami i przydałoby się żeby enemy bot miał też taką metodę, która będzie zwracała statystyki tak jak to jest w hero (i guess możesz to w sumie przenieść tą metodę do Creature, to będzie dostępna dla wszystkiego, co jest Creature i ma statystyki)

**Comment by Viciooo** [comment]
Zrobiłem creature abstract classą i dodałem get_statistics jako @abstractclass bo różni się trochę implementacją (bot nie ma Eq). W klasie Bot już jest o co prosiłeś
