### ISSUE TITLE
Wartości gold i exp w obiekcie Quest

### ISSUE THREAD

**Issue by atyranski** [miniprojectPythonGame/Merged#12]
Nie pamiętam czy chcieliśmy żeby exp i gold były jawne czy nie, ale myślę, że to spoko opcja, więc można by zapisywać w quest'cie wartość golda i exp'a

**Comment by Viciooo** [comment]
Trochę już oparłem logikę questów na tym, że generuje się to losowo i dla każdego bohatera gold i exp przychodzący jest customizowany. Wymagałoby to sporo zmian, które mogę zrobić jeśli jest to dla Ciebie ważne

**Comment by atyranski** [comment]
Ok dobra, to nie ma co
