### ISSUE TITLE
Item field 'quality'

### ISSUE THREAD

**Issue by atyranski** [miniprojectPythonGame/Merged#3]
Generalnie potrzebowałbym jeszcze w bazie w tabeli z itemkami takiej kolumny, która by określała jakość itema (legendary, epic i common, te trzy na razie mamy, także jakbyś dał radę jakoś je tam wstawić to byłbym mega wdzięczny)

**Comment by Viciooo** [comment]
Rozwiązane i działa
![image](https://user-images.githubusercontent.com/72527323/166819444-78c78e32-e4e9-4849-8eff-b09b590f6ea7.png)

![image](https://user-images.githubusercontent.com/72527323/166819469-2e4d23ac-17ee-4c11-8c90-4291faebf29c.png)
