### ISSUE TITLE
Quests additional fields

### ISSUE THREAD

**Issue by atyranski** [miniprojectPythonGame/Merged#4]
Do tabeli quests potrzebowałbym takich oto pól:
difficulty -> tam będą 3 możliwe wartości [easy, intermediate, hard]
treasure -> według pomysłu

**Comment by Viciooo** [comment]
to moja propozycja:
![image](https://user-images.githubusercontent.com/72527323/166813851-a0e8ef90-9f74-4fbe-afaf-511d83dd33f4.png)

**Comment by Viciooo** [comment]
Pracę nad questem rozpoczną po rozmowie dotyczącej walki
