### ISSUE TITLE
Items category

### ISSUE THREAD

**Issue by atyranski** [miniprojectPythonGame/Merged#5]
Potrzebowałbym żeby każdy item miał jeszcze pole określające z jakiej kategorii jest (tzn armor, weapon, magic) bo wtedy o wiele wygodniej będzie je generować odpowiednich sklepach

**Comment by Viciooo** [comment]
generować?
Itemki już dostarczam - chodzi o prezentowanie ich po stronie frontendu?

Dodałem item_type ale nie wiem czy o to chodzi
