### ISSUE TITLE
GearStatistics nie zostaje ustawione przy inicjalizacji

### ISSUE THREAD

**Issue by atyranski** [miniprojectPythonGame/Merged#7]
Chyba musisz przy get_storage dodać linijkę, żeby jeżeli item jest na tych pozycjach 0-10 (czyli są założone) to żeby dodawał ich gearStatistics, bo na razie jest tak, że jak się zaloguję i nawet jak jest założony jakiś itemek, to nie uwzględnia jego statystyk, muszę go zdjąć i dopiero założyć żeby go uwzględniło

**Comment by Viciooo** [comment]
fixed
